#!/bin/csh
echo "-- Testing your implementation of malloc --"
echo ""
echo "- If you have any problem in passing a test read the corresponding"
echo "- source file to understand what the test is checking"
echo ""
echo -n "********************* TEST MERGE ... "
read answ
./t0
echo -n "********************* TEST ALGORITHMS ... "
read answ
./t1
echo -n "********************* TEST EXTREME USAGE ... "
read ans
./t2
echo -n "********************* TEST MALLOC ... "
read ans
./t3
echo -n "********************* TEST MEMORY ... "
read ans
./t4
echo -n "********************* TEST REALLOC ... "
read ans
./t5
echo -n "********************* TEST CRASH  SIMPLE ... "
read ans
./t6
echo -n "********************* TEST CRASH COMPLEX ...  "
read ans
./t7

