//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.24 at 07:58:49 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.kth.se/ict/id2208/Matching", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package se.mattec.id2208.project.output;
