//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.01 at 07:41:27 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.ApplicantProfile.se", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED, xmlns={@XmlNs(prefix="ap", namespaceURI="http://www.ApplicantProfile.se")})
package se.mattec.id2208.hw1.employmentInfo;
import javax.xml.bind.annotation.XmlNs;

